applications:
  - alb_name_suffix: be
    service_port: 3000
    ec2s:
      - service_name: api-2a
        instance_type: t3a.medium
        ami_name: ""
        associate_public_ip_address: true
        subnet_type: "public"
        subnet_cidr: "10.0.1.0/24"
        ebs_block_device:
          volume_size: 30
  - alb_name_suffix: fe
    service_port: 3000
    ec2s:
      - service_name: web-2a
        instance_type: t3a.medium
        ami_name: ""
        associate_public_ip_address: true
        subnet_type: "public"
        subnet_cidr: "10.0.1.0/24"
        ebs_block_device:
          volume_size: 30
      - service_name: web-2b
        instance_type: t3.medium
        ami_name: ""
        associate_public_ip_address: true
        subnet_type: "public"
        subnet_cidr: "10.0.2.0/24"
        ebs_block_device:
          volume_size: 30
